<?php
declare(strict_types=1);
require_once __DIR__.'/config.php';require_once __DIR__.'/lib/booking.php';admin_only();
$notice='';$error='';$view=null;$order=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 $ref=trim((string)($_POST['ref']??''));$b=mt_booking_find_by_ref($ref);
 if(!$b)$error='Booking not found.'; else {
   if(isset($_POST['resend_receipt'])){$tmp=$b;$tmp['receipt_email_sent_at']=null;$ok=mt_send_payment_receipt($tmp);$notice=$ok?'Payment receipt resent.':'Email could not be sent.';}
   if(isset($_POST['resend_confirmation'])){$o=mt_booking_order($b);if(!$o)$error='Duffel order details are unavailable.';else{$tmp=$b;$tmp['confirmation_email_sent_at']=null;$ok=mt_send_confirmation($tmp,$o);$notice=$ok?'Confirmation resent.':'Email could not be sent.';}}
 }
}
if(!empty($_GET['view'])){$view=mt_booking_find_by_ref((string)$_GET['view']);if($view)$order=mt_booking_order($view);}
$rows=mt_booking_list(150);function ae($v){return h((string)$v);} ?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Flight Bookings | Mustafa Admin</title><link rel="stylesheet" href="assets/css/style.css"><style>body{background:#f4f7fb;color:#15314e;font-family:Inter,Arial}.ab{width:min(1280px,calc(100% - 30px));margin:28px auto}.ab-head{display:flex;justify-content:space-between;align-items:center}.ab a{color:#0759a8}.card{background:#fff;border:1px solid #dce5ed;border-radius:14px;padding:18px;margin:15px 0}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:9px;border-bottom:1px solid #e8eef4;text-align:left;font-size:12px}.table th{background:#f1f6fa}.pill{padding:4px 7px;border-radius:20px;background:#eaf7ef;color:#087443;font-weight:800}.btn{border:0;border-radius:7px;background:#073568;color:#fff;padding:8px 11px;font-weight:800;cursor:pointer;text-decoration:none!important;display:inline-block}.btn.alt{background:#fff;color:#073568;border:1px solid #bfcddd}.msg{padding:10px;border-radius:8px;background:#eaf7ef}.err{background:#fff0f0;color:#b42318}.actions{display:flex;gap:7px;flex-wrap:wrap}.detail-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.detail-grid div{background:#f5f8fb;padding:10px;border-radius:8px}@media(max-width:800px){.table{display:block;overflow:auto}.detail-grid{grid-template-columns:1fr 1fr}}</style></head><body><div class="ab"><div class="ab-head"><div><h1>Flight Bookings</h1><a href="admin.php">← Back to Admin</a></div><a class="btn alt" href="index.php" target="_blank">View Website</a></div><?php if($notice):?><div class="msg"><?=ae($notice)?></div><?php endif;?><?php if($error):?><div class="msg err"><?=ae($error)?></div><?php endif;?>
<?php if($view):$checkout=mt_booking_checkout($view);?><div class="card"><h2><?=ae($view['booking_ref'])?> · PNR <?=ae($view['pnr']?:'Pending')?></h2><div class="detail-grid"><div><b>Status</b><br><?=ae($view['status'])?></div><div><b>Customer</b><br><?=ae($view['customer_name'])?><br><?=ae($view['customer_email'])?></div><div><b>Amount</b><br><?=ae($view['currency'])?> <?=number_format((float)$view['amount'],2)?></div><div><b>Duffel Order</b><br><?=ae($view['duffel_order_id'])?></div></div><h3>Passengers</h3><?php foreach(($checkout['passengers']??[]) as $p):?><p><?=ae(trim(($p['title']??'').' '.($p['given_name']??'').' '.($p['family_name']??'')))?> · DOB <?=ae($p['born_on']??'')?></p><?php endforeach;?><h3>Itinerary</h3><?php foreach(mt_booking_itinerary($order) as $x):?><p><b><?=ae($x['airline'].' '.$x['flight'])?></b> · <?=ae($x['origin'])?> → <?=ae($x['destination'])?> · <?=ae($x['departing_at'])?></p><?php endforeach;?><div class="actions"><form method="post"><input type="hidden" name="ref" value="<?=ae($view['booking_ref'])?>"><button class="btn alt" name="resend_receipt">Resend Payment Receipt</button></form><?php if(($view['status']??'')==='confirmed'):?><form method="post"><input type="hidden" name="ref" value="<?=ae($view['booking_ref'])?>"><button class="btn" name="resend_confirmation">Resend Confirmation</button></form><?php endif;?></div></div><?php endif;?>
<div class="card"><table class="table"><tr><th>Date</th><th>Reference</th><th>Customer</th><th>Amount</th><th>Status</th><th>PNR</th><th>Stripe PI</th><th>Action</th></tr><?php foreach($rows as $r):?><tr><td><?=ae(substr((string)$r['created_at'],0,16))?></td><td><b><?=ae($r['booking_ref'])?></b></td><td><?=ae($r['customer_name'])?><br><?=ae($r['customer_email'])?></td><td><?=ae($r['currency'])?> <?=number_format((float)$r['amount'],2)?></td><td><span class="pill"><?=ae($r['status'])?></span></td><td><b><?=ae($r['pnr'])?></b></td><td><?=ae($r['payment_intent_id'])?></td><td><a class="btn alt" href="?view=<?=urlencode((string)$r['booking_ref'])?>">View Booking</a></td></tr><?php endforeach;?></table></div></div></body></html>
