<?php
require_once __DIR__.'/partials.php';
site_header('Flights');
?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<style>
.mf-page{background:#f4f8fc;min-height:760px;padding:46px 0 90px}.mf-wrap{width:min(1200px,calc(100% - 32px));margin:auto}.mf-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:20px}.mf-head h1{margin:0;font:800 38px Manrope,Inter,sans-serif;color:#08294f}.mf-head p{margin:7px 0 0;color:#6d8094}.mf-badge{background:#e2f4ff;color:#0877bd;border-radius:30px;padding:8px 12px;font-size:10px;font-weight:900}.mf-card{background:#fff;border:1px solid #dce6ef;border-radius:18px;padding:20px;box-shadow:0 18px 45px rgba(8,47,95,.08)}.mf-tabs{display:flex;gap:8px;margin-bottom:16px}.mf-tab{border:1px solid #d7e1eb;background:#fff;color:#526a80;border-radius:30px;padding:9px 15px;font-size:11px;font-weight:900;cursor:pointer}.mf-tab.active{background:#082f5f;border-color:#082f5f;color:#fff}.mf-row{display:grid;grid-template-columns:1.2fr 42px 1.2fr 1fr 1fr 1.15fr 150px;gap:9px}.mf-field{position:relative;border:1px solid #cedae5;border-radius:11px;padding:8px 11px;background:#fff}.mf-field label{display:block;font-size:9px;font-weight:900;color:#7a8da0}.mf-field input,.mf-field select{border:0;outline:0;background:transparent;width:100%;height:27px;color:#10253d;font:800 13px Inter,sans-serif}.mf-swap{align-self:center;width:36px;height:36px;border:1px solid #dbe5ee;background:#fff;color:#082f5f;border-radius:50%;font-weight:900}.mf-submit{border:0;border-radius:11px;background:linear-gradient(135deg,#1096e9,#0875ca);color:#fff;font-weight:900}.mf-airports{display:none;position:absolute;left:0;right:0;top:58px;z-index:110;background:#fff;border:1px solid #dce6ef;border-radius:12px;box-shadow:0 16px 45px rgba(8,47,95,.18);max-height:330px;overflow-y:auto}.mf-airports.open{display:block}.mf-airport{padding:11px 12px;border-bottom:1px solid #edf2f6;cursor:pointer}.mf-airport:hover{background:#f3f8fd}.mf-airport strong{display:block;font-size:12px}.mf-airport small{display:block;font-size:9px;color:#7c90a3}.mf-trigger{cursor:pointer}.mf-popup{display:none;position:absolute;right:0;top:58px;width:290px;z-index:120;background:#fff;border:1px solid #dce6ef;border-radius:14px;padding:15px;box-shadow:0 18px 50px rgba(8,47,95,.2)}.mf-popup.open{display:block}.mf-paxrow{display:flex;justify-content:space-between;align-items:center;padding:10px 0;border-bottom:1px solid #edf2f6}.mf-step{display:flex;align-items:center;gap:10px}.mf-step button{width:28px;height:28px;border-radius:50%;border:1px solid #ccd8e3;background:#fff}.mf-done{width:100%;margin-top:11px;border:0;border-radius:9px;background:#082f5f;color:#fff;padding:10px;font-weight:900}.mf-note{margin-top:13px;color:#71869a;font-size:10px}@media(max-width:700px){.mf-head{flex-direction:column;align-items:start}.mf-row{grid-template-columns:1fr}.mf-swap{display:none}.mf-submit{height:50px}}
</style>
<section class="mf-page"><div class="mf-wrap"><div class="mf-head"><div><h1>Search flights</h1><p>Compare live fares through Mustafa Travels.</p></div><span class="mf-badge">MULTI-PROVIDER READY</span></div>
<form class="mf-card" method="get" action="flight-results.php" id="mfForm">
<input type="hidden" name="trip_type" id="tripType" value="round"><input type="hidden" name="origin" id="originCode" value="BCN"><input type="hidden" name="destination" id="destinationCode" value=""><input type="hidden" name="adults" id="adultInput" value="1"><input type="hidden" name="children" id="childInput" value="0"><input type="hidden" name="infants" id="infantInput" value="0">
<div class="mf-tabs"><button type="button" class="mf-tab active" data-trip="round">Round trip</button><button type="button" class="mf-tab" data-trip="oneway">One way</button></div>
<div class="mf-row">
<div class="mf-field"><label>FROM</label><input type="text" id="originText" value="Barcelona (BCN)" placeholder="City or airport" autocomplete="off"><div class="mf-airports" id="originList"></div></div><button type="button" class="mf-swap" id="swap">⇄</button>
<div class="mf-field"><label>TO</label><input type="text" id="destinationText" placeholder="City or airport" autocomplete="off"><div class="mf-airports" id="destinationList"></div></div>
<div class="mf-field"><label>DEPARTURE</label><input type="text" name="departure" id="departure" placeholder="Select date" required></div><div class="mf-field" id="returnBox"><label>RETURN</label><input type="text" name="return_date" id="returnDate" placeholder="Select date" required></div>
<div class="mf-field mf-trigger" id="trigger"><label>TRAVELLERS & CABIN</label><strong id="travellerText">1 traveller</strong><small id="cabinText">Economy</small><div class="mf-popup" id="popup"><div class="mf-paxrow"><div><strong>Adults</strong><small>12+ years</small></div><div class="mf-step"><button type="button" data-pax="adult" data-d="-1">−</button><span id="adultCount">1</span><button type="button" data-pax="adult" data-d="1">+</button></div></div><div class="mf-paxrow"><div><strong>Children</strong><small>2–11 years</small></div><div class="mf-step"><button type="button" data-pax="child" data-d="-1">−</button><span id="childCount">0</span><button type="button" data-pax="child" data-d="1">+</button></div></div><div class="mf-paxrow"><div><strong>Infants</strong><small>Under 2</small></div><div class="mf-step"><button type="button" data-pax="infant" data-d="-1">−</button><span id="infantCount">0</span><button type="button" data-pax="infant" data-d="1">+</button></div></div><div class="mf-paxrow"><strong>Cabin</strong><select name="cabin" id="cabin"><option value="economy">Economy</option><option value="premium_economy">Premium Economy</option><option value="business">Business</option><option value="first">First</option></select></div><button type="button" class="mf-done" id="done">Done</button></div></div>
<button class="mf-submit" type="submit">Search flights</button></div><div class="mf-note">Airport search is now independent from the flight supplier.</div></form></div></section>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
document.addEventListener('DOMContentLoaded',()=>{const tripType=document.getElementById('tripType'),returnBox=document.getElementById('returnBox'),returnDate=document.getElementById('returnDate');function setTrip(t){tripType.value=t;document.querySelectorAll('.mf-tab').forEach(b=>b.classList.toggle('active',b.dataset.trip===t));if(t==='oneway'){returnBox.style.display='none';returnDate.removeAttribute('required');returnDate.value=''}else{returnBox.style.display='';returnDate.setAttribute('required','required')}}document.querySelectorAll('.mf-tab').forEach(b=>b.onclick=()=>setTrip(b.dataset.trip));let rp=flatpickr('#returnDate',{dateFormat:'Y-m-d',altInput:true,altFormat:'D, d M Y',minDate:'today',disableMobile:true});flatpickr('#departure',{dateFormat:'Y-m-d',altInput:true,altFormat:'D, d M Y',minDate:'today',disableMobile:true,onChange:(d,s)=>{if(s)rp.set('minDate',s)}});
async function airportSearch(q){const r=await fetch('api/airports.php?q='+encodeURIComponent(q));if(!r.ok)return[];const j=await r.json();return Array.isArray(j.results)?j.results:[]}function setupAirport(inputId,hiddenId,listId){const input=document.getElementById(inputId),hidden=document.getElementById(hiddenId),list=document.getElementById(listId);let timer=null,seq=0;input.addEventListener('input',()=>{hidden.value='';clearTimeout(timer);const q=input.value.trim();if(q.length<2){list.classList.remove('open');list.innerHTML='';return}timer=setTimeout(async()=>{const my=++seq,rows=await airportSearch(q);if(my!==seq)return;list.innerHTML='';rows.forEach(a=>{const el=document.createElement('div');el.className='mf-airport';el.innerHTML='<strong>'+a.city+' ('+a.code+')</strong><small>'+a.airport+' · '+a.country+'</small>';el.onclick=()=>{input.value=a.label;hidden.value=a.code;list.classList.remove('open')};list.appendChild(el)});list.classList.toggle('open',rows.length>0)},180)});document.addEventListener('click',e=>{if(!input.parentElement.contains(e.target))list.classList.remove('open')})}setupAirport('originText','originCode','originList');setupAirport('destinationText','destinationCode','destinationList');swap.onclick=()=>{const ot=originText.value,oc=originCode.value;originText.value=destinationText.value;originCode.value=destinationCode.value;destinationText.value=ot;destinationCode.value=oc};const trigger=document.getElementById('trigger'),popup=document.getElementById('popup');trigger.onclick=e=>{if(!e.target.closest('.mf-step')&&!e.target.closest('select')&&e.target.id!=='done')popup.classList.add('open')};done.onclick=e=>{e.stopPropagation();popup.classList.remove('open')};document.addEventListener('click',e=>{if(!trigger.contains(e.target))popup.classList.remove('open')});const state={adult:1,child:0,infant:0};function sync(){state.adult=Math.max(1,Math.min(9,state.adult));state.child=Math.max(0,Math.min(8,state.child));state.infant=Math.max(0,Math.min(state.adult,state.infant));adultInput.value=state.adult;childInput.value=state.child;infantInput.value=state.infant;adultCount.textContent=state.adult;childCount.textContent=state.child;infantCount.textContent=state.infant;const n=state.adult+state.child+state.infant;travellerText.textContent=n+(n===1?' traveller':' travellers')}document.querySelectorAll('[data-pax]').forEach(b=>b.onclick=e=>{e.stopPropagation();state[b.dataset.pax]+=+b.dataset.d;sync()});cabin.onchange=()=>cabinText.textContent=cabin.options[cabin.selectedIndex].text;mfForm.onsubmit=e=>{if(!originCode.value||!destinationCode.value){e.preventDefault();alert('Please select both airports from the suggestions.')}};setTrip('round');sync()});
</script>
<?php site_footer(); ?>
