<?php
declare(strict_types=1);
if (session_status() !== PHP_SESSION_ACTIVE) { session_start(); }
$today = date('Y-m-d');
$tomorrow = date('Y-m-d', strtotime('+1 day'));
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Hotel Search | Mustafa Travels & Tours</title>
<meta name="description" content="Search hotels worldwide with Mustafa Travels & Tours.">
<style>
:root{--navy:#0b1f3a;--blue:#155eef;--blue2:#2878ff;--gold:#c89b3c;--ink:#172033;--muted:#697386;--line:#e6eaf0;--soft:#f6f8fb;--white:#fff;--shadow:0 14px 40px rgba(11,31,58,.10)}
*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;color:var(--ink);background:#f4f7fb}a{text-decoration:none;color:inherit}
.topbar{background:var(--navy);color:#fff;padding:10px 22px;font-size:13px}.topbar .wrap,.nav .wrap,.hero .wrap,.content{max-width:1180px;margin:auto}.topbar .wrap{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}
.nav{background:#fff;border-bottom:1px solid var(--line)}.nav .wrap{min-height:72px;display:flex;align-items:center;justify-content:space-between;gap:24px;padding:0 22px}.brand{display:flex;align-items:center;gap:12px;font-weight:800;color:var(--navy)}.logo{width:44px;height:44px;border-radius:12px;background:linear-gradient(135deg,var(--navy),var(--blue));color:#fff;display:grid;place-items:center;font-weight:900}.brand small{display:block;color:var(--muted);font-weight:600;font-size:11px;margin-top:2px}.links{display:flex;gap:22px;align-items:center;font-size:14px;font-weight:700;color:#42516a}.links a.active{color:var(--blue)}
.hero{background:radial-gradient(circle at 85% 15%,rgba(200,155,60,.22),transparent 28%),linear-gradient(135deg,#0b1f3a 0%,#103567 58%,#155eef 100%);color:#fff;padding:58px 22px 98px}.hero h1{font-size:clamp(34px,5vw,56px);line-height:1.05;margin:0 0 14px;max-width:760px}.hero p{max-width:700px;margin:0;color:#dce8ff;font-size:17px;line-height:1.6}
.search-card{max-width:1180px;margin:-54px auto 0;padding:0 22px}.card{background:#fff;border:1px solid var(--line);border-radius:22px;box-shadow:var(--shadow);overflow:visible}.tabs{display:flex;gap:8px;padding:16px 18px 0}.tab{padding:11px 16px;border-radius:12px 12px 0 0;font-weight:800;color:#6b7485}.tab.active{color:var(--navy);background:#f8f9fc;border-bottom:3px solid var(--gold)}
.form{padding:22px 22px 24px;display:grid;grid-template-columns:2.1fr 1fr 1fr 1.2fr 1.15fr auto;gap:12px;align-items:end}.field{position:relative}label{display:block;font-size:12px;text-transform:uppercase;letter-spacing:.05em;font-weight:800;color:#667085;margin:0 0 7px 2px}.control{width:100%;height:54px;border:1px solid #d8dee8;border-radius:12px;padding:0 14px;outline:none;background:#fff;color:#182230;transition:.18s}.control:focus{border-color:#7da6ff;box-shadow:0 0 0 4px rgba(21,94,239,.10)}.search-btn{height:54px;min-width:132px;border:0;border-radius:12px;background:linear-gradient(135deg,var(--blue),var(--blue2));color:#fff;font-weight:900;cursor:pointer;padding:0 22px;box-shadow:0 8px 18px rgba(21,94,239,.22)}
.suggest{position:absolute;z-index:20;left:0;right:0;top:76px;background:#fff;border:1px solid var(--line);border-radius:14px;box-shadow:0 18px 40px rgba(16,24,40,.15);display:none;max-height:280px;overflow:auto}.suggest.show{display:block}.sitem{padding:12px 14px;cursor:pointer;border-bottom:1px solid #f0f2f5}.sitem:hover{background:#f6f9ff}.sitem strong{display:block;color:#182230}.sitem small{color:#7b8495}
.content{padding:46px 22px 70px}.section-title{display:flex;align-items:end;justify-content:space-between;gap:18px;margin-bottom:18px}.section-title h2{margin:0;color:var(--navy);font-size:28px}.section-title p{margin:5px 0 0;color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.destination{background:#fff;border:1px solid var(--line);border-radius:18px;overflow:hidden;min-height:180px;cursor:pointer;transition:.18s}.destination:hover{transform:translateY(-3px);box-shadow:var(--shadow)}.destination .visual{height:112px;display:flex;align-items:flex-end;padding:15px;color:#fff;font-weight:900;font-size:20px;background:linear-gradient(135deg,#173a69,#2368d8)}.destination:nth-child(2) .visual{background:linear-gradient(135deg,#4b2c20,#bd8b43)}.destination:nth-child(3) .visual{background:linear-gradient(135deg,#183c52,#1c8ca6)}.destination:nth-child(4) .visual{background:linear-gradient(135deg,#3c215f,#8b5fc0)}.destination .meta{padding:13px 15px;color:var(--muted);font-size:13px}.why{margin-top:44px;display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.benefit{background:#fff;border:1px solid var(--line);border-radius:18px;padding:22px}.icon{width:42px;height:42px;border-radius:12px;background:#eef4ff;color:var(--blue);display:grid;place-items:center;font-weight:900;margin-bottom:14px}.benefit h3{margin:0 0 6px;color:var(--navy)}.benefit p{margin:0;color:var(--muted);line-height:1.55;font-size:14px}.note{margin-top:26px;background:#fff8e8;border:1px solid #f1dfad;border-radius:14px;padding:14px 16px;color:#795d1e;font-size:13px}footer{background:#09182e;color:#cdd8ea;padding:34px 22px;font-size:13px}footer .wrap{max-width:1180px;margin:auto;display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}
@media(max-width:1050px){.form{grid-template-columns:repeat(3,1fr)}.search-btn{width:100%}}@media(max-width:760px){.links{display:none}.hero{padding-top:40px}.form{grid-template-columns:1fr}.grid,.why{grid-template-columns:1fr 1fr}}@media(max-width:520px){.grid,.why{grid-template-columns:1fr}.hero{padding-bottom:84px}}
</style>
</head>
<body>
<div class="topbar"><div class="wrap"><div>Mustafa Travels & Tours · Barcelona, Spain</div><div>Flights · Hotels · Umrah · Visa Services</div></div></div>
<nav class="nav"><div class="wrap"><a class="brand" href="/"><div class="logo">MT</div><div>Mustafa Travels & Tours<small>Travel made simple</small></div></a><div class="links"><a href="/">Home</a><a href="/flights-v3.php">Flights</a><a class="active" href="/hotels.php">Hotels</a><a href="/umrah.php">Umrah</a><a href="/contact.php">Contact</a></div></div></nav>
<section class="hero"><div class="wrap"><h1>Find the right hotel, at the right price.</h1><p>Search worldwide accommodation with live room availability, meal plans, cancellation conditions and clear pricing.</p></div></section>
<div class="search-card"><div class="card"><div class="tabs"><div class="tab active">Hotels</div></div>
<form class="form" action="/hotel-results.php" method="get" id="hotelSearchForm">
<div class="field"><label for="destination">Destination</label><input class="control" id="destination" name="destination" autocomplete="off" placeholder="City or destination" required><input type="hidden" id="city_code" name="city_code"><input type="hidden" id="country_code" name="country_code"><div class="suggest" id="suggestions"></div></div>
<div class="field"><label for="checkin">Check-in</label><input class="control" type="date" id="checkin" name="checkin" min="<?= htmlspecialchars($today) ?>" value="<?= htmlspecialchars($today) ?>" required></div>
<div class="field"><label for="checkout">Check-out</label><input class="control" type="date" id="checkout" name="checkout" min="<?= htmlspecialchars($tomorrow) ?>" value="<?= htmlspecialchars($tomorrow) ?>" required></div>
<div class="field"><label for="nationality">Guest nationality</label><select class="control" id="nationality" name="nationality" required><option value="PK" selected>Pakistan</option><option value="ES">Spain</option><option value="IN">India</option><option value="BD">Bangladesh</option><option value="SA">Saudi Arabia</option><option value="AE">United Arab Emirates</option><option value="GB">United Kingdom</option><option value="US">United States</option></select></div>
<div class="field"><label for="adults">Guests</label><select class="control" id="adults" name="adults"><option value="1">1 Adult · 1 Room</option><option value="2" selected>2 Adults · 1 Room</option><option value="3">3 Adults · 1 Room</option><option value="4">4 Adults · 1 Room</option></select><input type="hidden" name="rooms" value="1"><input type="hidden" name="children" value="0"></div>
<button class="search-btn" type="submit">Search Hotels</button></form></div></div>
<main class="content"><div class="section-title"><div><h2>Popular destinations</h2><p>Quick access to frequently requested destinations.</p></div></div>
<div class="grid"><div class="destination" data-city="Makkah/Mecca" data-code="127891" data-country="SA"><div class="visual">Makkah</div><div class="meta">Hotels near Masjid Al Haram & surrounding areas</div></div><div class="destination" data-city="Madinah" data-code="" data-country="SA"><div class="visual">Madinah</div><div class="meta">Accommodation near Masjid An Nabawi</div></div><div class="destination" data-city="Dubai" data-code="" data-country="AE"><div class="visual">Dubai</div><div class="meta">City hotels, resorts & apartments</div></div><div class="destination" data-city="Istanbul" data-code="" data-country="TR"><div class="visual">Istanbul</div><div class="meta">Central, historic & family-friendly stays</div></div></div>
<div class="why"><div class="benefit"><div class="icon">€</div><h3>Clear pricing</h3><p>Room rates, taxes and applicable supplements can be displayed before booking.</p></div><div class="benefit"><div class="icon">✓</div><h3>Live availability</h3><p>Rooms are checked against the supplier before the booking is finalized.</p></div><div class="benefit"><div class="icon">24</div><h3>Agency support</h3><p>Mustafa Travels & Tours remains your point of contact for booking assistance.</p></div></div>
<div class="note">Hotel availability and final rates are subject to revalidation at the PreBook stage before confirmation.</div></main>
<footer><div class="wrap"><div>© <?= date('Y') ?> Mustafa Travels & Tours</div><div>Barcelona · Spain</div></div></footer>
<script>
const destination=document.getElementById('destination'),cityCode=document.getElementById('city_code'),countryCode=document.getElementById('country_code'),box=document.getElementById('suggestions'),checkin=document.getElementById('checkin'),checkout=document.getElementById('checkout');
const seedCities=[{name:'Makkah/Mecca',code:'127891',country:'SA',sub:'Saudi Arabia'},{name:'Madinah',code:'',country:'SA',sub:'Saudi Arabia'},{name:'Dubai',code:'',country:'AE',sub:'United Arab Emirates'},{name:'Istanbul',code:'',country:'TR',sub:'Türkiye'},{name:'Barcelona',code:'',country:'ES',sub:'Spain'},{name:'Madrid',code:'',country:'ES',sub:'Spain'}];
function showSuggestions(items){if(!items.length){box.classList.remove('show');return}box.innerHTML=items.map(x=>`<div class="sitem" data-name="${x.name}" data-code="${x.code}" data-country="${x.country}"><strong>${x.name}</strong><small>${x.sub||x.country}</small></div>`).join('');box.classList.add('show')}
destination.addEventListener('input',()=>{cityCode.value='';const q=destination.value.trim().toLowerCase();if(q.length<1){box.classList.remove('show');return}showSuggestions(seedCities.filter(x=>(x.name+' '+x.sub).toLowerCase().includes(q)).slice(0,8))});
box.addEventListener('click',e=>{const item=e.target.closest('.sitem');if(!item)return;destination.value=item.dataset.name;cityCode.value=item.dataset.code||'';countryCode.value=item.dataset.country||'';box.classList.remove('show')});document.addEventListener('click',e=>{if(!e.target.closest('.field'))box.classList.remove('show')});
document.querySelectorAll('.destination').forEach(card=>card.addEventListener('click',()=>{destination.value=card.dataset.city||'';cityCode.value=card.dataset.code||'';countryCode.value=card.dataset.country||'';destination.scrollIntoView({behavior:'smooth',block:'center'});destination.focus()}));
checkin.addEventListener('change',()=>{if(!checkin.value)return;const d=new Date(checkin.value+'T00:00:00');d.setDate(d.getDate()+1);const minOut=d.toISOString().slice(0,10);checkout.min=minOut;if(!checkout.value||checkout.value<=checkin.value)checkout.value=minOut});
document.getElementById('hotelSearchForm').addEventListener('submit',e=>{if(checkout.value<=checkin.value){e.preventDefault();alert('Check-out date must be after check-in date.')}if(!destination.value.trim()){e.preventDefault();destination.focus()}});
</script>
</body></html>
