<?php require_once __DIR__.'/partials.php'; $packs=sb_select('umrah_packages','select=*&active=eq.true&order=featured.desc,id.desc'); site_header('Umrah & Hajj'); ?>
<section class="page-hero umrah-hero"><div class="container"><span class="eyebrow">UMRAH & HAJJ</span><h1>A spiritual journey, professionally arranged.</h1><p>Packages tailored around your dates, budget and hotel preferences.</p></div></section>
<section class="section"><div class="container"><div class="section-head centered"><div><span class="eyebrow dark">PACKAGE SERVICES</span><h2>Build your Umrah package</h2></div></div>
<div class="service-grid"><div class="service-card"><div class="service-icon">✈</div><h3>Flights</h3><p>Flexible airline and routing options.</p></div><div class="service-card"><div class="service-icon">▦</div><h3>Makkah & Madinah Hotels</h3><p>Economy to premium options based on distance and budget.</p></div><div class="service-card"><div class="service-icon">✓</div><h3>Visa Support</h3><p>Umrah visa assistance according to applicable requirements.</p></div><div class="service-card"><div class="service-icon">🚐</div><h3>Transport</h3><p>Jeddah–Makkah–Madinah and airport transfer options.</p></div></div>
<div class="center-actions"><a class="btn btn-primary btn-lg" href="contact.php?service=Umrah">Request Umrah Quote</a></div></div></section>

<?php if($packs): ?><section class="section section-soft"><div class="container"><div class="section-head"><div><span class="eyebrow dark">LIVE PACKAGES</span><h2>Current Umrah Packages</h2></div></div><div class="offers-grid">
<?php foreach($packs as $p): ?><article class="offer-card"><div class="offer-media" <?php if(!empty($p['image_url'])): ?>style="background-image:url('<?=h($p['image_url'])?>')"<?php endif;?>><span class="offer-badge"><?=h($p['duration']?:'Umrah Package')?></span></div><div class="offer-body"><small><?=h($p['airline'])?></small><h3><?=h($p['title'])?></h3><p><?=h($p['makkah_hotel'])?> · <?=h($p['madinah_hotel'])?></p><div class="offer-meta"><span><?=h($p['travel_date'])?></span><span><?=h($p['baggage'])?></span></div><div class="price">From <?=h($p['currency'])?> <?=number_format((float)($p['quad_price']?:$p['double_price']),0)?></div><a class="btn btn-dark" href="https://wa.me/<?=WHATSAPP?>?text=<?=urlencode('Please send details for Umrah package: '.$p['title'])?>" target="_blank">Ask on WhatsApp</a></div></article><?php endforeach;?>
</div></div></section><?php endif; ?>
<?php site_footer(); ?>