-- Run once in Supabase SQL Editor.
-- This table is server-only. RLS is enabled with no public policies.
create table if not exists public.flight_bookings (
  id bigint generated by default as identity primary key,
  booking_ref text not null unique,
  offer_id text not null,
  payment_intent_id text unique,
  status text not null default 'payment_pending',
  amount numeric(12,2) not null,
  currency text not null,
  customer_email text not null,
  customer_name text,
  checkout_json jsonb not null,
  receipt_email_sent_at timestamptz,
  confirmation_email_sent_at timestamptz,
  duffel_order_id text,
  pnr text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.flight_bookings enable row level security;

create index if not exists flight_bookings_payment_intent_idx
  on public.flight_bookings(payment_intent_id);
create index if not exists flight_bookings_status_idx
  on public.flight_bookings(status);
